/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CartStatusResponse { 
    /**
     * Status ID
     */
    cartStatusId: number;
    /**
     * Display name
     */
    displayName: string;
    /**
     * Code name
     */
    codeName: string;
    /**
     * Status description
     */
    description?: string;
}

