/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubscriptionProductSiteResponse } from './subscriptionProductSiteResponse';
import { CartSubscriptionItemUnitResponse } from './cartSubscriptionItemUnitResponse';
import { CartItemStatus } from './cartItemStatus';
import { SubscriptionProductResponse } from './subscriptionProductResponse';


export interface CartSubscriptionItemResponse { 
    /**
     * Cart Subscription Item ID
     */
    cartSubscriptionItemId: string;
    /**
     * Org ID
     */
    orgId: string;
    /**
     * Site ID
     */
    siteId: string;
    /**
     * Cart ID
     */
    cartId: string;
    /**
     * Unit ID
     */
    unitId: string | null;
    subscriptionProduct: SubscriptionProductResponse | null;
    subscriptionProductSite: SubscriptionProductSiteResponse | null;
    cartSubscriptionUnit: CartSubscriptionItemUnitResponse | null;
    cartSubscriptionItemStatus: CartItemStatus;
    /**
     * Total Price of Subscription Item
     */
    cartSubscriptionItemPrice: number;
}
export namespace CartSubscriptionItemResponse {
}


