/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CartLeaseItemResponse { 
    /**
     * Lease item ID
     */
    cartLeaseItemId: string;
    /**
     * Unit ID
     */
    unitId: string;
    /**
     * Site ID
     */
    siteId: string;
    /**
     * User-friendly display name for the unit; i.e unit name/label.
     */
    unitName: string;
    /**
     * The recurring monthly rate in the smallest currency unit (e.g. cents for USD).
     */
    price: number;
    /**
     * Document ID
     */
    documentId: string;
    /**
     * Starting date of the lease. I.e.
     */
    effectiveDate: string;
}

