/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeeResponse } from './feeResponse';


export interface CartFeeResponse { 
    /**
     * Cart Fee ID
     */
    cartFeeId: string;
    /**
     * Org ID
     */
    orgId: string;
    /**
     * Site ID
     */
    siteId: string;
    /**
     * Cart ID
     */
    cartId: string;
    fee: FeeResponse;
}

