/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartStatus } from './cartStatus';
import { CartFeeResponse } from './cartFeeResponse';
import { CartItemStatus } from './cartItemStatus';
import { CartSubscriptionItemResponse } from './cartSubscriptionItemResponse';
import { CartItemResponse } from './cartItemResponse';


export interface CartV2Response { 
    /**
     * Cart ID
     */
    cartId: string;
    /**
     * Org ID
     */
    orgId: string;
    /**
     * Site ID
     */
    siteId: string;
    /**
     * User ID
     */
    userId: string;
    /**
     * Account ID
     */
    accountId: string;
    cartStatus: CartStatus;
    notes: string | null;
    comments: string | null;
    cartSubscriptionItems: Array<CartSubscriptionItemResponse>;
    cartItems: Array<CartItemResponse>;
    cartFees: Array<CartFeeResponse>;
    cartItemsStatus: CartItemStatus;
    cartTotal: number;
}
export namespace CartV2Response {
}


