/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductSiteResponse } from './productSiteResponse';
import { CartItemStatus } from './cartItemStatus';
import { ProductResponse } from './productResponse';
import { CartItemTaxResponse } from './cartItemTaxResponse';


export interface CartItemResponse { 
    /**
     * Cart Item ID
     */
    cartItemId: string;
    /**
     * Org ID
     */
    orgId: string;
    /**
     * Site ID
     */
    siteId: string;
    /**
     * Cart ID
     */
    cartId: string;
    product: ProductResponse;
    productSite: ProductSiteResponse;
    /**
     * Quantity
     */
    quantity: number;
    cartItemStatus: CartItemStatus;
    cartItemTaxes: Array<CartItemTaxResponse>;
    /**
     * Total Price of Item(s) including Taxes
     */
    cartItemPrice: number;
}
export namespace CartItemResponse {
}


