/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CartItemTaxResponse { 
    /**
     * Cart Item Tax ID
     */
    cartItemTaxId: string;
    /**
     * Cart Item ID
     */
    cartItemId: string;
    /**
     * Tax Rate ID
     */
    taxRateId: string;
    /**
     * amount
     */
    amount: number;
    /**
     * amount
     */
    rate: number;
    /**
     * Tax description
     */
    description: string;
}

