/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCartRequest { 
    /**
     * Account ID
     */
    accountId?: string;
    /**
     * Payment provider ID
     */
    paymentProviderId?: string;
    /**
     * Currency code
     */
    currency?: string;
    /**
     * Notes about the shopping cart.
     */
    notes?: string;
    /**
     * Comments about the shopping cart.
     */
    comments?: string;
}

