/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateActiveCartRequest { 
    /**
     * Account ID
     */
    accountId: string;
    /**
     * Notes about the cart.
     */
    notes?: string;
    /**
     * Comments about the cart.
     */
    comments?: string;
}

