/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FeeResponse { 
    /**
     * Fee UUID
     */
    feeId: string;
    /**
     * Organization UUID
     */
    orgId: string;
    /**
     * Site UUID
     */
    siteId?: string;
    /**
     * The name of the fee.
     */
    name: string;
    /**
     * A description of the fee.
     */
    description: string;
    /**
     * A fixed ammount fee to add.
     */
    fixedAmount?: number;
    /**
     * A percent fee to add.
     */
    percentage?: number;
    /**
     * Standard Fee Type ID
     */
    standardFeeTypeId: string;
    /**
     * Codename of the standard fee type.
     */
    standardFeeType: FeeResponse.StandardFeeTypeEnum;
}
export namespace FeeResponse {
    export type StandardFeeTypeEnum = 'facility_fee' | 'late_fee' | 'convenience_fee';
    export const StandardFeeTypeEnum = {
        FacilityFee: 'facility_fee' as StandardFeeTypeEnum,
        LateFee: 'late_fee' as StandardFeeTypeEnum,
        ConvenienceFee: 'convenience_fee' as StandardFeeTypeEnum
    };
}


