/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartV2Response } from './cartV2Response';


export interface GetActiveCarts200Response { 
    data?: Array<CartV2Response>;
    success?: boolean;
    error?: object;
}

