/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductCategoryResponse } from './productCategoryResponse';


export interface GetProductCategories200Response { 
    data?: Array<ProductCategoryResponse>;
    success?: boolean;
    error?: object;
}

