/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubscriptionProductCategoryResponse } from './subscriptionProductCategoryResponse';


export interface GetSubscriptionProductCategories200Response { 
    data?: Array<SubscriptionProductCategoryResponse>;
    success?: boolean;
    error?: object;
}

