/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotFoundError404ResponseError } from './notFoundError404ResponseError';


export interface NotFoundError404Response { 
    readonly data: Array<string>;
    readonly success: boolean;
    error: NotFoundError404ResponseError;
}

