/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductResponse { 
    /**
     * Id of the product
     */
    productId: string;
    /**
     * Name of the product
     */
    name: string;
    /**
     * Description of the product
     */
    description: string;
    /**
     * Path to an image of the product
     */
    imagePath: string | null;
    /**
     * Product Category Id
     */
    productCategoryId: string;
    /**
     * Payment provider ID
     */
    paymentProviderId: string;
    /**
     * Time of creation
     */
    createdAt: string;
    /**
     * userId of who created the product
     */
    createdBy: string;
    /**
     * Time of the last update
     */
    updatedAt: string | null;
    /**
     * userId of who updated the product
     */
    updatedBy: string | null;
}

