/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductItemRequest { 
    /**
     * Product Name
     */
    name: string;
    /**
     * Product Description
     */
    description: string;
    /**
     * Image path for the product
     */
    imagePath?: string;
}

