/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionProductSiteResponse { 
    /**
     * Id of the subscription product
     */
    subscriptionProductSiteId: string;
    /**
     * Price
     */
    price: number;
    /**
     * Product Category Id
     */
    productCategoryId: string;
    /**
     * Identifier of subscription product.
     */
    subscriptionProductId: string;
    /**
     * Site Id
     */
    siteId: string;
    /**
     * Organization Id
     */
    orgId: string;
}

