/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubscriptionProductResponse } from './subscriptionProductResponse';


export interface SubscriptionProductCategoryResponse { 
    /**
     * The unique identifier for the subscription product category.
     */
    subscriptionProductCategoryId: string;
    /**
     * The identifier of the organization that the subscription product category belongs to.
     */
    orgId: string;
    /**
     * The name of the subscription product category.
     */
    name: string;
    /**
     * The display order of the subscription product category.
     */
    displayOrder: number;
    /**
     * The subscription products in this subscription product category.
     */
    subscriptionItems: Array<SubscriptionProductResponse>;
}

