/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionProductResponse { 
    /**
     * Id of the subscription product
     */
    subscriptionProductId: string;
    /**
     * Name of the subscription product
     */
    name: string;
    /**
     * Description of the Subscription product
     */
    description: string;
    /**
     * Path to an image of the subscription product
     */
    imagePath: string | null;
    /**
     * Product Category Id
     */
    productCategoryId: string;
    /**
     * Meta Data
     */
    metaData: object;
    /**
     * Time of creation
     */
    createdAt: string;
    /**
     * userId of who created the product
     */
    createdBy: string;
    /**
     * Time of the last update
     */
    updatedAt: string | null;
    /**
     * userId of who updated the product
     */
    updatedBy: string | null;
}

