/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubscriptionProductItemRequest } from './subscriptionProductItemRequest';


export interface UpdateProductCategoryRequest { 
    /**
     * The name of the product category.
     */
    name?: string;
    /**
     * The display order of the product category.
     */
    displayOrder?: number;
    /**
     * Subscription products to be created within the category.
     */
    subscriptionItems?: Array<SubscriptionProductItemRequest>;
}

