/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartTaxResponse } from './cartTaxResponse';


export interface UpdateCartTax201Response { 
    data?: Array<CartTaxResponse>;
    success?: boolean;
    error?: object;
}

