/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateFeeRequest { 
    /**
     * The name of the fee.
     */
    name: string;
    /**
     * A description of the fee.
     */
    description: string;
    /**
     * A fixed ammount fee to add.
     */
    fixedAmount?: number;
    /**
     * A percent fee to add.
     */
    percentage?: number;
    /**
     * Standard Fee Type ID
     */
    standardFeeTypeId: string;
}

