/**
 * ManageSpace Commerce API
 * ManageSpace Commerce API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateSubscriptionProductCategoryRequest { 
    /**
     * The name of the subscription product category.
     */
    name?: string;
    /**
     * The display order of the subscription product category.
     */
    displayOrder?: number;
}

